title: TV Intro Detection
description: This project tries to detect intros of tv series by comparing pairs of episodes to find the largest common subset of frames.

remote_theme: just-the-docs/just-the-docs

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

