name: Build & Push Jellyfin Intro Scanner & Skipper

on:   
  push:
    branches:
      - master

env:
  IMAGE_NAME_SCANNER: jellyfin-intro-scanner
  IMAGE_NAME_SKIPPER: jellyfin-intro-skipper
  REGISTRY: ghcr.io

jobs:
  Scanner_Build_and_Push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_SCANNER }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_SCANNER }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile_Jellyfin-Intro-Scanner
          
  Skipper_Build_and_Push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_SKIPPER }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_SKIPPER }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile_Jellyfin-Intro-Skipper
